### ISSUE TITLE
Walkthrough / user onboarding do Pilot

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#10]
## Problema
Hoje não temos um sistema de boas-vindas nem um guia que conduza o usuário na nova dashboard.
Temos uma ferramenta comprada para tal, AppCues, mas precisamos definir o conteúdo e o que efetivamente mostraremos no primeiro momento para os clientes.

## Possível Solução
Comparar as mudanças entre dashboard antiga e nova e elencar os pontos mais importantes de esclarecer para o usuário, visando não deixar ninguém perdido no novo ambiente.
É importante deixar esses três aspectos claros para os clientes  em cada cenário:

• Benefício entregue ao usuário - É o problema que estaremos resolvendo. Ex: novo sistema de filtros para transações.

• Como - É a explicação de como faremos isso. Ex: Mudando a forma como as transações são filtradas, simplificando o uso.

• Onde - É a demostração prática do caminho para alcançar o objetivo desejado. Ex: explicar o uso prático dos novos filtros.

Precisamos também conduzir o usuário para que perceba claramente o valor que estamos agregando com nossa solucão e seguida precisamos garantir que ele seja capaz de efetivamente executar a solução que estamos propondo.

## Dependências Externas
Acredito que não haja nenhuma.

## Qual o risco de não entregar
Criação de tickets no RC com dúvidas e reclamações que podem ser mitigadas com um processo de Onboarding bem resolvido.

Também podemos aumentar a insatisfação com nosso produto, caso algum cliente se sinta perdido inicialmente enquanto se adapta as mudanças.

## Critérios de Aceite
- [ ] Definir os problemas mais importantes que solucionamos em cada tela nova
- [ ] Escolher como mostraremos essas melhorias para os clientes. Ex: Texto puro na home falando sobre o que mudou? Passo-a-passo guiado para que ele acompanhe cada área nova?
- [ ] Fluxos devidamente aplicados na Pilot via AppCues
- [ ] Garantir que em menos de 5 minutos de uso o usuário passe por ao menos um AHA e um WOW moment com sucesso.

## Subtasks
- [ ] Encontrar/definir o "benefício", o "como", e o "onde"
 de cada melhoria.

## Review
- [ ] 1 review de outro designer;
- [ ] 1 review externo;

**Comment by flaviolee** [comment]
Para construir um walkthrough ideal, precisamos entender quais foram as mudanças em cada tela e quais seções já disponibilizaremos para o cliente.

Só assim poderemos elencar a prioridade das funções que precisam ser exibidas no primeiro contato com a Pilot.

Por conta disso, estou adicionando uma **Dependencia externa** "definir o escopo das telas" e uma **subtask** "mapear os fluxos/sitemaps de cada seção do pilot", pra conseguir ter visão do que está ou não no ponto ideal de ser passado para o cliente.

**Comment by flaviolee** [comment]
Issue congelada até a criação dos sitemaps e definição do escopo das telas.
