### ISSUE TITLE
Avaliar possibilidade de mudar o status de boletos após data de vencimento

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#11]
## Problema
Um cliente passou um feedback sugerindo a possibilidade de mudar o status de um boleto para "não pago" ou "vencido" quando passasse da data de vencimento, já que hoje não é possível cancela-lo.

A falta dessa sinalização torna dificil a visualização entre boletos ainda a vencer e os que já deveriam ter sido pagos e vão querer outras medidas do cliente por conta disso.

Prints do feedback no slack:
![screen shot 2018-09-26 at 16 33 00](https://user-images.githubusercontent.com/29930809/46104519-e6c36900-c1a9-11e8-841c-535605ffaa94.png)

![image](https://user-images.githubusercontent.com/29930809/46104528-eaef8680-c1a9-11e8-9471-f018064f53d5.png)

## Possível Solução
Entender melhor o cenário para ver se a solução ideal seria mesmo essa criação de "status para boleto"

## Dependências Externas
Conversar com o time responsável, Ghostbuster, pois como dito no print, seria necessário alterar a forma como boletos são conciliados.

## Qual o risco de não entregar
O cliente continuar com dificuldades de tratar seus boletos vencidos e não conseguir cobrar devidamente seus customers.

## Critérios de Aceite
Medir os prós e contras de ter essa tarefa feita, definindo impacto para o cliente e tamanho do esforço para conclui-la.

## Subtasks
- [ ] Entender o problema com Ghosbusters
- [ ] Definir a solução

## Review
- [ ] 1 review de design
- [ ] 2 reviews externo (Ghostbusters + RC)
