### ISSUE TITLE
Exibir feedback de erro no fluxo de saque

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#12]
## Problema
Hoje não exibimos em lugar nenhum quando um saque tem algum problema que tenha sido originado no Banco. Geralmente são problemas envolvendo erro nos dados inputados no Banco, não na Pagar.me.

Essa situação foi levantada numa conversa do Slack.
Seguem prints com o registro:

<img src="https://user-images.githubusercontent.com/29930809/45835404-68b21e80-bce0-11e8-8621-a5e2c081950b.png"  alt="Print 1" width="100" height="100">

<img src="https://user-images.githubusercontent.com/29930809/45835406-68b21e80-bce0-11e8-937e-a2d77e5bbf97.png"  alt="Print 2" width="100" height="100">

<img src="https://user-images.githubusercontent.com/29930809/45835407-68b21e80-bce0-11e8-8261-27a74fb94d6f.png"  alt="Print 3" width="100" height="100">

## Possível Solução
Mapear esses cenários de erro num fluxo de saque e encontrar a melhor forma de deixar o cliente ciente disso ou evitar que aconteçam.

## Dependências Externas
Os erros aqui podem ser gerados por ações do cliente em ambientes onde não temos controle, como num processo de cadastro de dados num Banco. É preciso entender como isso se dá para saber até onde podemos ajudar nossos clientes.

## Qual o risco de não entregar
Continuarmos recebendo reclamações sobre erros no saque que não são causados pela gente ou por nossos sistema.

Continuarmos também usando tempo do RC e do pessoal de Finops para gerar comprovantes apenas para mostrar que o erro vem do Banco, não na Pagar.me

## Critérios de Aceite
Ter o cenário todo compreendido e os erros possíveis de acontecerem num fluxo de saque devidamente mapeados, junto de soluções para esses erros. 

## Subtasks
- [ ] Entender os erros que podem acontecer num fluxo de saque
- [ ] Definir soluções ou métodos de prevenção para cada erro
- [ ] Definir o formato ideal de feedback desses erros para o cliente

## Review
- [ ] 1 reviews interno - design
- [ ] 2 reviews externos - RC + Finops
