### ISSUE TITLE
Time de risco quer visualizar o status "revisada manulamente " na lista de transações

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#13]
## Problema
O time de risco levantou uma questão sobre a exibição do status das transações revisadas manualmente, pedindo para que fosse possível identifica-las já na pagina de lista de transações.

Não houve nenhuma reclamação ou pedido dos clientes quanto a isso.

Precisamos entender a viabilidade e o custo de uma alteração nessa forma de exibição para ajudar o Risco.

Mais detalhes nessa issue: https://github.com/pagarme/gatekeepers/issues/578

## Possível Solução
Entender o impacto da mudança na forma de visualização e se isso afetaria o cliente de alguma forma.

## Dependências Externas
Entender como o time de risco interage com essas transações.
Entender qual o fluxo das transações dentro do Pagar.me em seus diversos cenários

## Qual o risco de não entregar
O time de risco ter mais trabalho ao tentar identificar essas transações.
O cliente não ter como filtrar/buscar por transações que passaram pela revisão manual.

## Critérios de Aceite
Ter uma noção clara do que o Risco vê nessas transações e entender se a ideia proposta é mesmo a solução ideal.

## Subtasks
- [x] Entender como essa alteração afetaria o cliente
- [x] Entender o esforço para essa alteração
- [ ] Desenhar fluxos dos status das transações dentro do Pagar.me
- [x] Definir a melhor resposta para essa questão

## Review
- [ ] 1 review interno - design
- [ ] 2 reviews externos - Gatekeepers, Risco

**Comment by flaviolee** [comment]
Estou tentando desenhar um fluxo do caminhos possiveis para uma transação percorrer, deixando essa visualização mais simplificada, pra conseguir entender qual seria de verdade a forma correta de sanar essa demanda do Risco.

Vendo isso, percebi algumas inconsistências na nomenclatura que estamos usando em alguns dos status, que podem acabar confundindo o cliente. Exemplo: quando uma transação está em revisão manual, o cliente escolhe entre RECUSAR ou APROVAR, porém os status que podem derivar dai são RECUSADA ou AUTORIZADA.

Fora isso, percebemos que hoje o clienta também não consegue filtrar por transações oriunas de revisão manual depois de aprovadas ou recusadas. Isso pode ser interessante pra ele em alguns cenários.

**Comment by flaviolee** [comment]
Essa issue foi criada em decorrência dessa aqui: https://github.com/pagarme/gatekeepers/issues/578#issuecomment-423356598

**Comment by flaviolee** [comment]
Estudando o problema percebi duas coisas aqui que podem afetar o cliente, entao alterei o campo ##Qual o risco de não entregar.

Uma questão é que hoje clientes do antifraude não conseguem filtrar por transações que passaram por revisão manual, perdendo o tracking das mesmas e dificultando um controle sobre isso.

Outra questão é detectada é que as opções exibidas durante o processo de aceitar ou negar uma transação manualmente podem confundir o cliente por conta da nomenclatura da ação, RECUSAR ou APROVAR, bem diferente dos status que a transação assume após a escolha de uma dessas opções, que é RECUSADA ou AUTORIZADA.

**Comment by flaviolee** [comment]
Baseado nisso, também atualizei as **Dependências externas** já que precisei buscar com outras pessoas e times informações sobre os fluxos de uma transação pra entender a melhor forma de mostrar o status que o Risco pediu.

**Comment by flaviolee** [comment]
> Estou tentando desenhar um fluxo do caminhos possiveis para uma transação percorrer, deixando essa visualização mais simplificada, pra conseguir entender qual seria de verdade a forma correta de sanar essa demanda do Risco.

Baseado nisso acrescentei a subtask "desenhar fluxos das transações"

**Comment by flaviolee** [comment]
Conversei com Gatekeepers.
Essa tarefa não é uma prioridade para eles e também enxergam um grande esforço aqui pra fazer isso funcionar da maneira correnta, sendo que faríamos alterações na Pilot primeiramente para o Risco ter essa visibilidade melhor.

Eles deram a sugestão de talvez pensar em algo na dashboard admin atual, ajudando o Risco por lá, mas também seria algo custoso por precisar de um planejamento mais elaborado, já que a dash atual não é o foco para se trabalhar com o antifraude.

Falta conversar com o Risco pra entender se o problema pode ser resolvido de alguma outra maneira e confirmar se é o entendido até aqui mesmo.

**Comment by flaviolee** [comment]
Falei com a @marina-moorsel pra entender melhor as necessidades do Risco.

Descobri que eles possuem uma outra maneira de checar essas informações, então hoje eles não estão deixando de conseguir ver o que precisam.

Como o custo pra analisar o contexto e desenvolver a solução é alto para um retorno pequeno, não vamos executar essa tarefa nesse momento.

Fica o registro então de que num futuro podemos analisar a viabilidade dos status serem remapeados para dar visibilidade ao cliente sobre o que passou pela revisão manual, ajudando a filtrar e depois a acompanhar os passos das transações.

**Comment by flaviolee** [comment]
Ideia de melhorar a filtragem de transações que passaram pela revisão manual registrada nessa issue https://github.com/pagarme/design/issues/15 .

**Comment by flaviolee** [comment]
Tudo resolvido. Issue nova aberta para dar seguimento num melhor momento aos problemas identificados.
