### ISSUE TITLE
Melhorar a exibição de transações que passaram pela revisão manual

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#15]
## Problema
Estudando o caso da issue #13, descobrimos que o cliente não tem como filtrar/buscar por transações que passaram pela revisão manual depois que o status delas mudou. (De autorizada para Paga, ou sofreu um chargeback depois, por exemplo).

Hoje ele consegue ver esse tipo de informação apenas pela timeline de eventos, dentro do detalhe de cada transação.

## Possível Solução
Criar labels/status novos que mostrem a passagem pela decisão da revisão manual.

## Dependências Externas
Nenhuma

## Qual o risco de não entregar
O cliente continuar sem ter como filtrar essa informação de maneira simples.

## Critérios de Aceite
Entender a melhor forma de mostrar essa informação pro cliente, deixando claro que uma transação passou pela revisão manual.

## Subtasks
- [ ] Elencar quais status se relacionam com uma transação após passar pela revisão manual
- [x] Desenhar o fluxo ideal para o cliente enxergar essa informação

## Review
- [ ] 1 review interno - design;
- [ ] 1 review externo - dev;
