### ISSUE TITLE
Matriz de funcionalidades

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#17]
## Problema
Precisamos deixar claro o funcionamento de cada feature que pretendemos implementar no Pilot, facilitando a visualização para todos.

## Possível Solução
Criar uma matriz de funcionalidades para cada seção da Pilot.

## Qual o risco de não entregar
Perdermos visibilidade e controle sobre a performance ideal das funções levantadas, dificultando o processo de acompanhamento e testes de qualidade.

## Critérios de Aceite
Descrever as funções esperadas de cada seção, detalhando seu escopo e suas peculiaridades.

## Subtasks
Após o esclarecimento das informações de negócios normalmente os devs quebram o card em forma 
- [ ] Matriz de transações
- [ ] Matriz de extrato
- [ ] Matriz de Link de pagamentos
- [ ] Matriz de Venda digitada/adicionar transacao
- [ ] Matriz de Clientes
- [ ] Matriz de Recebedores
- [ ] Matriz de Recorrencia
- [ ] Matriz de Configuracoes

## Review
- [ ] 1 review interno;
