### ISSUE TITLE
Rollout da dash para Portal Terra

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/design#18]
## Contexto
Temos um grupo de clientes que têm necessidade de escopo menor do que o da dashboard completa, e que nos dão a oportunidade de trazê-los 100% direto na nova Dashboard assim que são credenciados.

Eles nos permitirão entender como a nova dashboard os atende, e já entregar valor com o projeto um cliente de cada vez.

Este cliente irá criar transações apenas pelo seu e-commerce do Portal Terra. Ele não terá contato com a API, não criará transações, não terá acesso a venda digitada, nem recorrência, recebedores, etc.

Sua interação com a Dashboard será apenas para entender melhor sua posição financeira, e sacar o resultado de suas vendas.

Esta Milestone é parte do Rollout gradual da Pilot.

## Possível Solução
Sendo um cliente e-commerce básico, eis o que ele precisa:

- Lista de transações, com filtros e opção de exportar;
- Detalhes de transação, com operações padrão;
- Extrato;
- Saque;
- Suporte do RC via chat e email.

## Dependências Externas
Este cliente terá suporte do RC normalmente, como outros clientes, mas para isso precisamos preparar o RC para ter as ferramentas de chat e email funcionando de acordo.

## Qual o risco de não entregar
Perdermos a janela de oportunidade de oferecer Pilot a um grupo de clientes, diminuindo a utilidade do projeto como um todo. Esse é um projeto de crescimento e não sobrevivência, portanto a questão aqui é o quanto a gente evitaria de crescer se ele não saísse.

## Critérios de Aceite
Todas as subtasks especificadas abaixo estarem finalizadas.

## Subtasks
- [ ] Entender o perfil desse usuário
- [ ] Mapeamento do fluxo de seções
- [ ] Verificar as configurações que o usuário vai realizar pelo Portal e quais serão pela Dashboard
- [ ] Mapear métricas que iremos extrair desse funil
- [ ] Montar vídeo tutorial
- [ ] Pensar como sinalizar a versão da dashboard, para facilitar como o RC atenderá esse cliente

**Como refinamento do que já está desenvolvido:**

- [ ] Revisar colunas da tela de Transações
- [ ] Testar os status de transação
- [ ] Testar os cenários da timeline de detalhe da transação
- [ ] Verificar os botões contextuais de cada status de transação
- [ ] Resumo do período - estudar paliativo

## Review
Todo card criado precisa receber a definição de quantos reviews (internos ou externos) ele precisa receber para considerarmos o card pronto para seguir na coluna Waiting Deploy, ex:
- [ ] 1 review de ux;
- [ ] 1 review de BL;
- [ ] Review do rc e auto credenciamento.
