### ISSUE TITLE
Mapeamento de Personas 

### ISSUE THREAD

**Issue by Fausto-Junior** [pagarme/design#8]
## Problema
Hoje os times não conhecem os clientes (pessoas) que utilizam nossos produtos. Sabemos que a Empresa X é um cliente do Pagar.me, mas quem é a pessoa dessa empresa que olha para o financeiro, por exemplo?;

## Possível Solução 
Persona é a representação fictícia dos nossos clientes. Ela é baseada em dados reais, motivações, objetivos, desafios e preocupações. Essas personas servem como referência, assim conseguimos criar empatia e então engajar todo o time para pensar em novas e melhores soluções.;

## Dependências Externas
Precisamos garantir que a coleta de dados (entrevista/questionário) chegue nas pessoas certas. Acredito que o RC, Account managers e os BLs consigam ajudar muito nessa tarefa.; 

## Qual o risco de não entregar
O risco é continuarmos sem conhecer os clientes (pessoas) que utilizam nossos produtos, e isso é muito ruim se queremos desenvolver produtos com `fit for purpose` e um design centrado nos usuários.; 

## Subtasks
- [x] Definir questionário
- [ ] Definir modelo de persona 
- [ ] Levantar possíveis clientes (pessoas) para a coleta de dados (de 8 a 12 pessoas) 
- [ ] Realizar as entrevistas/aplicar questionário
- [ ] Compilar os dados e abstrair para os perfis de persona

## Review
- [ ] BL do time;
- [ ] 3 outros BLs;
